import Head from "next/head";
import Crime from "../components/Crime";
import useSWR, { SWRConfig } from "swr";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

export default function Home() {
  return (
    <div>
      <Head>
        <title>Police Crime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <SWRConfig value={{ fetcher }}>
          <Crime />
        </SWRConfig>
      </section>
    </div>
  );
}
